# Generated by Django 2.2.19 on 2023-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(related_name='products', through='products.ProductSpecificationValue', to='products.Specification', verbose_name='характеристики'),
        ),
    ]
